const Map<String, String> ar = {
  'BusinessConcept': 'Business Concept',
  'Home': 'الرئيسية',
  'Services': 'خدماتنا',
  'WhyUs': 'لماذا نحن',
  'OurGoals': 'أهدافنا',
  'OurPortfolio': 'أعمالنا',
  'OurClient': 'عملائنا',
  'ContactUs': 'اتصل بنا',
  'HeaderOne': 'اجعل أفكارك تنبض بالحياة',
  'HeaderTwo': 'تطوير البرامج والمنتجات المخصصة\nبتقنية ممتازة',
  'HeaderThree':
      'يمكننا مساعدتك في إضفاء الحيوية على منتجك من خلال تصميم وتطوير تطبيقات رائعة للويب والجوال',
  'HeaderFour': 'بحاجة الى موقع مخصص كامل؟',
  'HeaderFive': ' هل لديك مشروع؟ لنتحدث.',
  'ServiceSectionTitle': 'نحن نقدم أنواع مختلفة من الخدمة لك',
  'ServiceSectionSubTitle':
      'نقدم لك مجموعة متنوعة ومتكاملة من خدمات البرمجة من أجل توفير نظام عمل متكامل وسلس.',
  'UniqueAppUI': 'واجهة مستخدم فريدة للتطبيق',
  'ClientDashboard': 'لوحة تحكم العميل',
  'WebDevelopment': 'تطوير الشبكة',
  'AwesomeDesign': 'تصميم رائع',
  'EasyCustomise': 'بناء مهام مخصصه',
  'SuperFast': 'سريع جدا',
  'UpdateNotification': 'تحديث الاشعارات',
  'HighResolution': 'دقة عالية',
  'ExtremeSecurity': 'آمن',
  'GetInTouch': 'ابقى على تواصل',
  'Name': 'الاسم',
  'YourName': 'أدخل أسمك',
  'EnterYourEmail': 'أدخل بريدك الإلكتروني',
  'Email': 'البريد الإلكتروني',
  'Message': 'الرسالة',
  'SubmitNow': 'أرسل',
  'ContactDisc': 'سيسعد فريقنا بالتواصل معك والإجابة على استفساراتك',
  'ReadDetails': 'Read Details',
};
