const Map<String, String> en = {
  'BusinessConcept': 'Business Concept',
  'Home': 'Home',
  'Services': 'Services Us',
  'WhyUs': 'Why Us',
  'OurGoals': 'Our Goals',
  'OurPortfolio': 'Our Portfolio',
  'OurClient': 'Our Clients',
  'ContactUs': 'Contact Us',
  'HeaderOne': 'BRING YOUR IDEAS TO LIFE',
  'HeaderTwo':
      'Custom Product & Software Development\nWith Excellent Technology',
  'HeaderThree':
      'We can help you bring your product to life by Design and develop awesome apps for web and mobile',
  'HeaderFour': 'Need a full custom website?',
  'HeaderFive': ' Got a project? Let\'s talk.',
  'ServiceSectionTitle': 'We Provide Various Kind of Service for you',
  'ServiceSectionSubTitle':
      'We Offer You a diverse and integrated set of programming services in order to provide integrated and seamless work system.',
  'UniqueAppUI': 'Unique App Ui',
  'ClientDashboard': 'Client Dashboard',
  'WebDevelopment': 'Web Development',
  'AwesomeDesign': 'Awesome Design',
  'EasyCustomise': 'Easy Customise',
  'SuperFast': 'Super Fast',
  'UpdateNotification': 'Update Notification',
  'HighResolution': 'High Resolution',
  'ExtremeSecurity': 'Extreme Security',
  'GetInTouch': 'Get In Touch',
  'Name': 'Name',
  'YourName': 'Your Name',
  'EnterYourEmail': 'Enter Your Email',
  'Email': 'Email',
  'Message': 'Message',
  'SubmitNow': 'Submit Now',
  'ContactDisc':
      'Our team will be happy to Communicate with you and answer your inquiries',
  'ReadDetails': 'Read Details',
};
